#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-vCard
version:      1.3
version_from: 
installdirs:  site
requires:
    File::Slurp:                   9999.04
    Text::vFile::asData:           0.01
    Test::More:                    0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
