#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-vCard
version:      1.1
version_from: 
installdirs:  site
requires:
    Text::vFile::asData:           0.01
    Test::More:                    0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
