---
abstract: 'Module for parsing and creating vCards (RFC 2426) address'
author:
  - 'Leo Lapworth'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-vCard
no_index:
  directory:
    - t
    - inc
requires:
  File::Slurp: 9999.04
  MIME::QuotedPrint: 3.07
  Test::More: 0.1
  Text::vFile::asData: 0.07
resources:
  bugtracker: https://github.com/ranguard/text-vcard/issues
  repository: https://github.com/ranguard/text-vcard
version: 2.11
