#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-vCard
version:      1.4
version_from: 
installdirs:  site
requires:
    Test::More:                    0.1
    Text::vFile::asData:           0.01
    File::Slurp:                   9999.04

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
