--- #YAML:1.0
name:               Text-vCard
version:            2.05
abstract:           Module for parsing and creating vCards (RFC 2426) address
author:
    - Leo Lapworth
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.1
requires:
    File::Slurp:          9999.04
    MIME::QuotedPrint:    3.07
    perl:                 5.006
    Text::vFile::asData:  0.05
resources:
    repository:  http://github.com/ranguard/text-vcard
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
