---
abstract: 'a package to edit and create a single vCard (RFC 2426)'
author:
  - 'Leo Lapworth'
  - 'Eric Johnson (kablamo)'
build_requires:
  Data::Dumper: '0'
  Directory::Scratch: '0'
  Test::More: '0'
  Test::Most: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-vCard
requires:
  Carp: '0'
  Encode: '0'
  File::Slurp: '9999.04'
  MIME::Base64: '3.07'
  MIME::QuotedPrint: '3.07'
  Moo: '0'
  Path::Class: '0'
  Text::Wrap: '0'
  Text::vFile::asData: '0.07'
  URI: '0'
  Unicode::LineBreak: '0'
  base: '0'
  perl: '5.006'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/ranguard/text-vcard/issues
  repository: https://github.com/ranguard/text-vcard
version: '3.01'
